/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdvancedUpload: typeof import('./src/components/AdvancedUpload.vue')['default']
    AnalyticsChart: typeof import('./src/components/AnalyticsChart.vue')['default']
    BatchOperations: typeof import('./src/components/BatchOperations.vue')['default']
    BatchOperationsGeneric: typeof import('./src/components/BatchOperationsGeneric.vue')['default']
    ContentPreview: typeof import('./src/components/ContentPreview.vue')['default']
    CrudTable: typeof import('./src/components/CrudTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    GlobalSearch: typeof import('./src/components/GlobalSearch.vue')['default']
    InfiniteScroll: typeof import('./src/components/InfiniteScroll.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    PageLayout: typeof import('./src/components/PageLayout.vue')['default']
    QuestionForm: typeof import('./src/components/QuestionForm.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    TinyMCEEditor: typeof import('./src/components/TinyMCEEditor.vue')['default']
    TokenStatus: typeof import('./src/components/TokenStatus.vue')['default']
    VirtualTable: typeof import('./src/components/VirtualTable.vue')['default']
  }
}
